config/routes.rb
Rails.application.routes.draw do
  root to: 'experiences#index' 
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    resources :bookings
    resources :likes
  end
  resources :experiences do
    resource :likes
    resources :bookings
    resources :reviews, only: [:new, :create]
  end
  resources :hosts
  resources :maps, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :experience
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :booking_users, through: :bookings, source: :user
  # バリデーションと関連付け
  has_many :likes, dependent: :destroy
  # experience.liked_usersでexperienceをいいねしているユーザの一覧を取得できる
  has_many :liked_users, through: :likes, source: :user
  
  has_many :reviews, dependent: :destroy
  
  mount_uploader :image, ImageUploader

  # geocoderの適用
  # :addressを登録した際にgeocoderが緯度経度ののカラムにも自動的に値を入れてくれる
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # いいねしているか判定
  def liked_by?(user)
    likes.find_by(user_id: user.id).present?
  end

  scope :start_after, -> (datetime) {
    datetime = datetime.to_datetime
    where('start_datetime > ?', datetime)
  }

  class << self
    def ransackable_scopes(auth_object = nill)
      [:start_after]
    end
  end
end

app/models/host.rb
class Host < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :user_id, uniqueness: {
    scope: :experience_id,
    message: "は同じ投稿に２回以上いいねはできません"
  }
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :experience
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :booking_experiences, through: :bookings, source: :experience
  # バリデーションと関連付け
  has_many :likes, dependent: :destroy
  # user.liked_postsでuserがいいねしている体験一覧を取得できるようになる
  has_many :liked_experiences, through: :likes, source: :experience
  
  has_many :review, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # first_nameを追記
  validates :first_name, presence: true
  # last_nameを追記
  validates :last_name, presence: true
  # ImageUploaderとusersテーブルのimageカラムと連携
  mount_uploader :image, ImageUploader

  #ゲストユーザーログイン
  def self.guest
    find_by(email: 'test@example.com') do |user|
      user.password = 'password'
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end
  
  def new
    @booking = Booking.new
    redirect_to action: :create
  end

  def create
    Booking.create(user_id: current_user.id, experience_id: params[:experience_id])
    render("bookings/create")
  end

  def edit
    @booking.find(params[:id])
  end

  def update
    booking = @booking.find(params[:id])
    booking.update(booking_params)
    redirect_to action: :index
  end

  def destroy
    booking = Booking.find_by(user_id: current_user.id, experience_id: params[:experience_id])
    booking.destroy
    render("bookings/destroy")
  end

  private

  def booking_params
    params.require(:bookings).permit(:user_id,:experience_id)
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :authenticate_user!, except: :index
  
  PER_PAGE = 10
  def index
    search_option = {
     start_after: params[:start_after]
    }
    @q = Experience.ransack(params[:q], search_option)
    @experiences = @q.result.page(params[:page]).page(params[:page]).per(PER_PAGE)
    # @liked_experience_ids = current_user.likes.pluck(:experience_id)
  end

  def show
    @experience = Experience.find(params[:id])
    @reviews = @experience.reviews
    @review = Review.new
  end

  def new
    @experience = Experience.new
  end

  def create
    experience = Experience.new(experience_params)
    experience.user_id = current_user.id
    experience.save!
    redirect_to action: :index
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    experience = Experience.find(params[:id])
    experience.update(experience_params)
    redirect_to action: :index
  end

  def destroy
    experience = Experience.find(params[:id])
    experience.destroy
    redirect_to action: :index
  end

  private
  def experience_params
    params.require(:experience).permit(:title, :fee, :prefecture, :region, :address, :content, :start_datetime, :finish_datetime, :language, :image)
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
    @hosts = Host.order(:id)
  end

  def new
    @host = Host.new
  end

  def create
    Host.create(host_params)
    redirect_to action: :index
  end

  def edit
    @host = Host.find(params[:id])
  end

  def update
    host = Host.find(params[:id])
    host.update(host_params)
    redirect_to action :index
  end

  def destroy
    host = Host.find(params[:id])
    host.destroy
    redirect_to action: :index
  end

  private
  def host_params
    params.require(:host).permit(:first_name, :last_name, :email, :image_url, :password )
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def index
    @likes = current_user.likes
  end

  def create
    @experience = Experience.find(params[:experience_id])
    current_user.likes.create!(experience_id: @experience.id)
  end

  def destroy
    @experience = Experience.find(params[:experience_id])
    current_user.likes.find_by(experience_id: @experience.id).destroy!
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # before_action :set_map, only: [:index]

  def create
    @map = Map.new(map_params)
    if @map.valid?
      map.save
    else
      render :new
    end
  end

  def index
    @map = Map.new(map_params)
  end

  private

  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:address)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @experience = Experience.find(params[:experience_id])
    @review = Review.new
  end

  def create
    Review.create(review_params)
    redirect_to controller: :experiences, action: :index
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating).merge(experience_id: params[:experience_id], user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:id)
  end
  
  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    redirect_to action: :index
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to action: :index
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to action: :index
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/_dislike.html.erb
<%= link_to experience_likes_path(@experience), method: :post, remote: true do %>
  <i class="far fa-heart unlike-btn"></i>保存 
<% end %>

app/views/experiences/_like.html.erb
<%= link_to experience_likes_path(@experience), method: :delete, remote: true do %>
  <i class="fas fa-heart like-btn"></i>保存済
<% end %>

app/views/experiences/_map.html.erb
<% #地図の表示 %>
<div id='map'></div>

<style>
  #map {
    height: 600px;
    width: 600px;
  }
</style>

<script>
  let map
  let geocoder
  const display = document.getElementById('display')

  function initMap(){
      geocoder = new google.maps.Geocoder()
      test ={lat:<%= @experience.latitude %>, lng:<%= @experience.longitude %>};
      map = new google.maps.Map(document.getElementById('map'),{
        // latが緯度、lagが軽度
        center: test,
        // 数値は０から２１まで指定
        zoom: 12,
      });
      contentString = '住所：<%= @experience.address %>';
      infowindow = new google.maps.InfoWindow({
        content: contentString
      });

      // positionに指定した座標にピンを表示させてます
      marker = new google.maps.Marker({
        position:  test,
        map: map,
        title: contentString
      });

      marker.addListener('click', function(){
        infowindow.open(map,marker);
      });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeO6xn5fNT67yK0PGW_emEonxmpdeiYf8&callback=initMap" async defer></script>

app/views/experiences/create.html.erb
<h1>登録完了</h1>
<%= link_to "一覧画面へ", "/experiences" %>

app/views/experiences/edit.html.erb
<p>更新</p>
<%= form_with model: @experience, url:"/experiences/#{@experience.id}", method: :patch, local: true do |f| %>
  <p>タイトル：<%= f.text_field :title %></p>
  <p>料金：<%= f.text_field :fee %></p>
  <p>都道府県：<%= f.text_field :prefecture %></p>
  <p>地方：<%= f.collection_select :region, Region.all, :name, :name, include_blank: "選択してください" %></p>
  <p>住所：<%= f.text_field :address %></p>
  <p>内容：<%= f.text_area :content %></p>
  <p>開始日時：<%= f.datetime_field :start_datetime %></p>
  <p>終了日時：<%= f.datetime_field :finish_datetime %></p>
  <p>対応言語：<%= f.text_field :language %></p>
  <p>画像：<%= f.file_field :image %></p>
  <%= f.submit "登録" %>
<% end %>

app/views/experiences/index.html.erb
<div class="main-container">
  <h1>身近にある、特別な茶摘み体験。</h1>
</div>

<div class="container my-5">
    <h2 class="text-center mb-5">「茶摘みを体験しよう」</h2>
    <p class="text-center">日本のお茶は、機械で摘むことがほとんどですが、</p>
    <p class="text-center">なかには人の手で摘むお茶もあります。</p>
    <p class="text-center">ひとつひとつ芽を見ながら、丁寧に摘んていくので、とても時間と労力がかかりますが、</p>
    <p class="text-center">そのぶん、美味しく旨味のあるお茶になります。</p>
    <p class="text-center">Tearip-ティリップ-は、茶摘みをしてお茶を飲んでもらうという"旅"を通して、</p>
    <p class="text-center">お茶好きになってほしいという思いが込もった、茶摘み体験の予約サービスです。</p> 
</div>

  <% if @experiences.any? %>
      <div class="row">
        <% @experiences.each do |experience| %>
          <div class="card border-0 col-md-3" style="width: 18rem">
            <%= link_to(experience_path(experience),{class: "card-link"}) do %>
                <%= image_tag experience.image.url, size: '400x250',class:"card-img-top rounded" %>
                <div class="card-body">
                  <% #星表示 %>
                  <%= image_tag(asset_path('star-on.png')) %>
                  <% #平均点 %>
                  <%= experience.reviews.average(:rating).to_f.round(2) %>
                  <% #口コミ件数 %>
                  (<%= experience.reviews.count %>).
                  <%= experience.prefecture %><br>
                  <h5 class="card-title"><%= experience.title %></h5>
                  １人当たり￥<%= experience.fee %>から
                </div>
            <% end %>
          </div>
        <% end %>
      </div>
  <% else %>
    <p>お探しの体験はありませんでした</p> 
  <% end %>
  <%= paginate @experiences %>

app/views/experiences/new.html.erb
<h1>体験をホストする</h1>
<%= form_with model: @experience, class: "card col-md-6", local: true do |f| %>
  <div class="card-body">
    <div class="form-row">
      <div class="form-group col-md-12">
        <label for="inputTitle">タイトル</label>
        <%= f.text_field :title, class: "form-control", id: "inputTitle", placeholder: "タイトル" %>
      </div>
      <div class="form-group col-md-12">
        <label for="inputFee">料金</label>
        <%= f.text_field :fee, class: "form-control", id: "inputFee", placeholder: "料金" %>
      </div>
      <div class="form-group col-md-12">
        <label for="InputPrefecture">都道府県</label>
        <%= f.text_field :prefecture, class: "form-control", id: "InputPrefecture", placeholder: "都道府県" %>
      </div>
      <div class="form-group col-md-12">
        <label for="InputRegion">地方</label>
        <%= f.text_field :region, class: "form-control", id: "InputRegion", placeholder: "地方" %>
      </div>
      <div class="form-group col-md-12">
        <label for="InputAddress">住所</label>
        <%= f.text_field :address, class: "form-control", id: "InputAddress", placeholder: "住所" %>
      </div>
      <div class="form-group col-md-12">
        <label for="InputContent">内容</label>
        <%= f.text_area :content, class: "form-control", id: "InputContent", placeholder: "内容" %></p>
      </div>
      <div class="form-group col-md-12">
        <label for="InputStartDatetime">開始日時</label>
        <%= f.datetime_field :start_datetime, class: "form-control", id: "InputStartDatetime" %>
      </div>
      <div class="form-group col-md-12">
        <label for="InputFinishDatetime">終了日時</label>
        <%= f.datetime_field :finish_datetime, class: "form-control", id: "InputFinishDatetime" %>
      </div>
      <div class="form-group col-md-12">
        <label for="InputLanguage">ガイド言語</label>
        <%= f.text_field :language, class: "form-control", id: "InputLanguage", placeholder: "ガイド言語" %>
      </div>
      <div class="form-group col-md-12">
        <label for="InputImage">画像</label>
        <%= f.file_field :image, class: "form-control-file", id: "InputImage" %>
      </div>
    </div>
    <%= f.submit "掲載をはじめる", class:"btn btn-success" %>
  </div>
<% end %>

app/views/experiences/show.html.erb
<div class="container">
  <div class="card border-0" style="width: 800px">
    <% #お気に入り機能 %>
    <p id="experience-<%= @experience.id %>", class="text-right">
    <% if @experience.liked_by?(current_user) %>
      <%= render partial: "like", experience: @experience %>
    <% else %>
      <%= render partial: "dislike", experience: @experience %>
    <% end %>
    </p>
    <% #イメージ画像 %>
    <p><%= image_tag @experience.image.url, size: '800x500', class: "rounded" %></p>
    <h2 class="card-title">
      <%= @experience.title %>
    </h2>
    <div class="card-body">
      <div class="card-text">
      <% #星表示 %>
          <%= image_tag(asset_path('star-on.png')) %>
      <% #平均点 %>
      <%= @experience.reviews.average(:rating).to_f.round(2) %>
      <% #口コミ件数 %>
      (<%= @experience.reviews.count %>).
      <%= @experience.prefecture %>
    </div>
  </div>
<div>

<div class="container">
  <div class="border-top my-4 py-4">
    <h3><%= @experience.user.first_name %>&nbsp;<%= @experience.user.last_name %>さんがホストする体験</h3>
    <div class="card-group">
      <div class="card border rounded mx-2 py-3">
        <div class="box-part text-center"><i class="far fa-clock fa-3x" aria-hidden="true"></i></div>
        <div class="card-body text-center">
          <h5 class="card-title">時間</h5>
          <p class="card-text">１日</p>
        </div>
      </div>
      <div class="card border rounded mx-2 py-3">
        <div class="box-part text-center"><i class="far fa-comment fa-3x" aria-hidden="true"></i></div>
        <div class="card-body  text-center">
            <h5 class="card-title">ガイド言語</h5>
            <p class="card-text"><%= @experience.language %></p>
          </div>
        </div>
      <div class="card border rounded mx-2 py-3">
        <div class="box-part text-center"><i class="fas fa-utensils fa-3x" aria-hidden="true"></i></div>
        <div class="card-body text-center">
            <h5 class="card-title">食べ物</h5>
            <p class="card-text">お茶、おにぎり</p>
          </div>
        </div>
    </div>
  </div>
    <% #体験できること %>
    <div class="border-top my-4 py-4">
      <h3>体験できること</h3>
      <p><%= @experience.content %><p>
    </div>

    <% #地図の表示 %>
    <div class="border-top my-4 py-4">  
        <h3>実施場所</h3>
        <%= render partial: "map", class: "rounded" %>
    </div>

  <% #予約機能 %>
  <div class="border-top my-4  py-4">
    <h3>予約可能な日付から選択する</h3>
    <div class="card rounded" style="width: 18rem">
      <div class="card-body">
        <h5 class="card-title">
          <%= @experience.start_datetime.strftime('%-m月%-d日') %><br>
        </h5>
        <p class="card-text">
          <%= @experience.start_datetime.strftime('%H:%M') %>
          〜<%= @experience.finish_datetime.strftime('%H:%M') %>
        </p>
        <p><%= @experience.fee %>円/人</p>
        <% if Booking.where(user_id: current_user.id, experience_id: params[:id]).any? %>
            <%= link_to 'キャンセル', experience_booking_path(@experience.id), method: :delete, class: "btn btn-success", data: {confirm: "予約をキャンセルしますか？"} %>
          </button>
        <% else %>
            <%= link_to '予約', experience_bookings_path(@experience.id), method: :post, class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>

  <% #口コミ機能 %>
  <div class="border-top py-4">
    <h3>
      <% #星表示 %>
        <%= image_tag(asset_path('star-on.png')) %>
      <% #平均点 %>
      <%= @experience.reviews.average(:rating).to_f.round(2) %>
      <% #口コミ件数 %>
      (<%= @experience.reviews.count %>件のレビュー)
    </h3>

    <% @reviews.each do |review| %>
      <div class="card my-4 rounded">
        <div class="card-body"> 
          <p><%= review.user.first_name %>&nbsp;<%= review.user.last_name %></p>
          <p><%= review.content %></p>
        <!--星評価-->
        <div id="star-rate-<%= review.id %>"></div>
          <script>
          $('#star-rate-<%= review.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            readOnly: true,
            score: <%= review.rating %>,
          });
          </script> 
        </div>
      </div> 
    <% end %>
  </div>
</div>