config/routes.rb
Rails.application.routes.draw do
  root to: 'experiences#index' 
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users do
    resources :bookings
    resources :likes
  end
  resources :experiences do
    resource :likes
    resources :bookings
    resources :reviews, only: [:new, :create]
  end
  resources :hosts
  resources :maps, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :experience
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :booking_users, through: :bookings, source: :user
  # バリデーションと関連付け
  has_many :likes, dependent: :destroy
  # experience.liked_usersでexperienceをいいねしているユーザの一覧を取得できる
  has_many :liked_users, through: :likes, source: :user
  
  has_many :reviews, dependent: :destroy
  
  mount_uploader :image, ImageUploader

  # geocoderの適用
  # :addressを登録した際にgeocoderが緯度経度ののカラムにも自動的に値を入れてくれる
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # いいねしているか判定
  def liked_by?(user)
    likes.find_by(user_id: user.id).present?
  end

  scope :start_after, -> (datetime) {
    datetime = datetime.to_datetime
    where('start_datetime > ?', datetime)
  }

  class << self
    def ransackable_scopes(auth_object = nill)
      [:start_after]
    end
  end
end

app/models/host.rb
class Host < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :user_id, uniqueness: {
    scope: :experience_id,
    message: "は同じ投稿に２回以上いいねはできません"
  }
end

app/models/map.rb
class Map < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :experience
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :booking_experiences, through: :bookings, source: :experience
  # バリデーションと関連付け
  has_many :likes, dependent: :destroy
  # user.liked_postsでuserがいいねしている体験一覧を取得できるようになる
  has_many :liked_experiences, through: :likes, source: :experience
  
  has_many :review, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # first_nameを追記
  validates :first_name, presence: true
  # last_nameを追記
  validates :last_name, presence: true
  # ImageUploaderとusersテーブルのimageカラムと連携
  mount_uploader :image, ImageUploader

  #ゲストユーザーログイン
  def self.guest
    find_by(email: 'test@example.com') do |user|
      user.password = 'password'
    end
  end
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  def index
    @hosts = Host.order(:id)
  end

  def new
    @host = Host.new
  end

  def create
    Host.create(host_params)
    redirect_to action: :index
  end

  def edit
    @host = Host.find(params[:id])
  end

  def update
    host = Host.find(params[:id])
    host.update(host_params)
    redirect_to action :index
  end

  def destroy
    host = Host.find(params[:id])
    host.destroy
    redirect_to action: :index
  end

  private
  def host_params
    params.require(:host).permit(:first_name, :last_name, :email, :image_url, :password )
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def index
    @likes = current_user.likes
  end

  def create
    @experience = Experience.find(params[:experience_id])
    current_user.likes.create!(experience_id: @experience.id)
  end

  def destroy
    @experience = Experience.find(params[:experience_id])
    current_user.likes.find_by(experience_id: @experience.id).destroy!
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # before_action :set_map, only: [:index]

  def create
    @map = Map.new(map_params)
    if @map.valid?
      map.save
    else
      render :new
    end
  end

  def index
    @map = Map.new(map_params)
  end

  private

  def set_map
    @map = Map.find(params[:id])
  end

  def map_params
    params.require(:map).permit(:address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:id)
  end
  
  def new
    @user = User.new
  end

  def create
    User.create(user_params)
    redirect_to action: :index
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to action: :index
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to action: :index
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © All rights reserved by Takao Yamasaki.
  <div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light fixed-top">
  <div class="col-3" >
    <% #ロゴ %>
    <%= link_to root_path, class: "navbar-brand" do %>
      Tearip
      <i class="fas fa-leaf"></i>
    <% end %>
  </div>

  <% #検索窓 %>
  <div class="col-6">
    <div class="container">
      <% if current_page?(root_path) %>
        <%= search_form_for(@q, {class: "form-horizonal"}) do |f| %>
          <div class="input-group input-group-lg">
            <%= f.search_field :prefecture_cont, class: "form-control", placeholder: "行き先はどちら？" %>
            <%= f.date_field :start_after, class: "form-control", placeholder: "希望日を追加" %>
            <span class="input-group-append">
              <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
              </button>
            </span>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% #ユーザー画像 %>
  <% #image_tag current_user.image.url %>

  <% #ハンバーガーメニュー %>
  <div class="col-3">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="#navbarSupportedContent" aria-expand="false" aria-label="Toggle navigation" style="float:right">
      <span class="navbar-toggler-icon">
      </span>
    </button>
  </div>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <%= link_to "予約中の体験", user_bookings_path(current_user.id), class: "nav-item nav-link active" %>
      <%= link_to "お気に入りの体験" ,user_likes_path(current_user.id), class: "nav-item nav-link active" %>
      <%= link_to "体験をホストする", new_experience_path, class: "nav-item nav-link active" %>
      <%= link_to "アカウントを編集する", edit_user_registration_path, class: "nav-item nav-link active" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} , class: "nav-item nav-link active" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active" %>
      <%= link_to "登録する", new_user_registration_path, class: "nav-item nav-link active" %>
    <% end %>
  </div>
</nav>

app/views/layouts/_search_form.html.erb
<dl class="searchbox">
  <%= search_form_for @q do |f| %>
    <dt><%= f.search_field :prefecture_cont, placeholder: "行き先はどちらですか？" %></dt>
    <dt><%= f.date_field :start_after, placeholder: "希望日を追加" %></dt>
    <dd><%= f.submit "探す"%>
  <% end %>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teaparty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=devise-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= favicon_link_tag('favicon.jpg') %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <div class="base-container">
         <%= yield %>
      </div>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>